= SM_8mosfet Library for Arduino =

This library allows you to turn on or off individual mosfets or all 8 in the same time, you can read the mosfets state. To use it you will need one S-Bridge card and one 8-Mosfets card. 

For more information about this library please visit the [README](https://github.com/SequentMicrosystems/8mosfet-rpi/blob/master/arduino/README.md)

== License ==

Copyright (c) Sequent Microsystems All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
